name: DDoSDefender
version: '1.601'
main: ac.kosko.dDoSDefender.DDoSDefender
api-version: '1.20'
authors: [ Koskolonium ]
description: Injects a sophisticated custom network handler into the network pipeline to enhance your server's protection.
depend: [ ProtocolLib ]