# Default settings are suitable for most servers with fewer than 300 active players.
#
# For servers with 300+ active players:
# Recommended queue size: 50
# Recommended processing limit: 10
#
# If using Free TCPShield Plan:
# Recommended queue size: 15
# Recommended processing limit: 3
#
# If you are using Premium+ TCPShield or similar external DDoS protection:
# It is recommended to use the recommended settings for 300+ active players above,
# Then set your "Connections per second" in your control panel to be between 11-15.
#
# Note: Increasing the queue size without appropriately adjusting the processing limit
# can cause players to experience longer connection times.

queue:
  size: 25  # Maximum number of players that can wait in the connection queue
process:
  limit: 5  # Number of player connections processed per second